import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const books = [
  {
    title: "Clean Code",
    author: "robert c. martin",
    price: 59.99,
    stock: 12,
    description: "a handbook of agile software craftsmanship.",
    imageUrl: "http://bit.ly/4kSDo0J",
    featured: true,
    bestSellers: true,
    bookRating: 4.5,
    genre: "science",
    reviews: 124,
    pages: 464,
    publisher: "prentice hall",
    publishedDate: "2008-08-01",
    isbn: "9780132350884",
  },
  {
    title: "The Pragmatic Programmer",
    author: "andy hunt",
    price: 49.99,
    stock: 8,
    description: "classic book on pragmatic software development principles.",
    imageUrl: "http://bit.ly/4lWVlwM",
    featured: true,
    bestSellers: true,
    bookRating: 4.7,
    genre: "science",
    reviews: 200,
    pages: 352,
    publisher: "addison-wesley",
    publishedDate: "1999-10-30",
    isbn: "9780201616224",
  },
  {
    title: "Introduction To Algorithms",
    author: "thomas h. cormen",
    price: 89.0,
    stock: 5,
    description:
      "comprehensive textbook covering algorithms and data structures.",
    imageUrl: "http://bit.ly/4kXTBSg",
    featured: false,
    bestSellers: true,
    bookRating: 4.3,
    genre: "science",
    reviews: 320,
    pages: 1312,
    publisher: "mit press",
    publishedDate: "2009-07-31",
    isbn: "9780262033848",
  },
  {
    title: "You Don't Know JS",
    author: "kyle simpson",
    price: 34.99,
    stock: 15,
    description: "a deep dive into javascript internals.",
    imageUrl: "http://bit.ly/3H5Bqwg",
    featured: true,
    bestSellers: false,
    bookRating: 4.0,
    genre: "science",
    reviews: 150,
    pages: 278,
    publisher: "oreilly media",
    publishedDate: "2015-12-27",
    isbn: "9781491904244",
  },
  {
    title: "design patterns",
    author: "erich gamma",
    price: 69.0,
    stock: 9,
    description: "elements of reusable object-oriented software.",
    imageUrl: "http://bit.ly/4595DTi",
    featured: false,
    bestSellers: true,
    bookRating: 4.2,
    genre: "science",
    reviews: 180,
    pages: 395,
    publisher: "addison-wesley",
    publishedDate: "1994-10-21",
    isbn: "9780201633610",
  },
  {
    title: "refactoring",
    author: "martin fowler",
    price: 54.0,
    stock: 7,
    description: "improving the design of existing code.",
    imageUrl: "http://bit.ly/3U0xOhX",
    featured: false,
    bestSellers: false,
    bookRating: 4.1,
    genre: "science",
    reviews: 90,
    pages: 448,
    publisher: "pearson",
    publishedDate: "2018-11-19",
    isbn: "9780134757599",
  },
  {
    title: "structure and interpretation of computer programs",
    author: "harold abelson",
    price: 75.0,
    stock: 6,
    description: "foundational book on programming and computer science.",
    imageUrl: "http://bit.ly/3Uv6Mzs",
    featured: false,
    bestSellers: false,
    bookRating: 4.6,
    genre: "science",
    reviews: 110,
    pages: 657,
    publisher: "mit press",
    publishedDate: "1996-07-25",
    isbn: "9780262510875",
  },
  {
    title: "deep learning",
    author: "ian goodfellow",
    price: 99.0,
    stock: 4,
    description: "a detailed look into the field of deep learning.",
    imageUrl: "http://bit.ly/45cEfUt",
    featured: true,
    bestSellers: false,
    bookRating: 4.4,
    genre: "science",
    reviews: 70,
    pages: 800,
    publisher: "mit press",
    publishedDate: "2016-11-18",
    isbn: "9780262035613",
  },
  {
    title: "html and css",
    author: "jon duckett",
    price: 39.0,
    stock: 10,
    description: "visual guide to web development with html and css.",
    imageUrl: "http://bit.ly/40E4At2",
    featured: true,
    bestSellers: true,
    bookRating: 4.1,
    genre: "science",
    reviews: 98,
    pages: 490,
    publisher: "john wiley & sons",
    publishedDate: "2011-11-08",
    isbn: "9781118008188",
  },
  {
    title: "effective java",
    author: "joshua bloch",
    price: 64.0,
    stock: 6,
    description: "best practices for the java programming language.",
    imageUrl: "https://shorturl.at/LCmPT",
    featured: false,
    bestSellers: true,
    bookRating: 4.5,
    genre: "science",
    reviews: 120,
    pages: 416,
    publisher: "addison-wesley",
    publishedDate: "2018-01-06",
    isbn: "9780134685991",
  },
];
async function main() {
  await prisma.book.createMany({
    data: books,
  });
  console.log("✅ Books are seeded.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
